debug:
  config: false
  replace: false
  blockstore: false

chance:
  wither-skeleton: 0.8

excluded-entity-types: [ ARMOR_STAND, PLAYER ]

zones: {}

items: {}

loots: {}

mobs: {}

objectives: {}

potions: {}