name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
database: true
main: nu.nerd.beastmaster.BeastMaster
softdepend: [ Multiverse-Core ]
depend: [ WorldEdit, BlockStore ]

permissions:
  beastmaster.console:
    description: Permission to administer the plugin. This permission only makes sense for those with console access.
    default: op

  beastmaster.zone:
    description: Permission to use the /beast-zone command.
    default: op

  beastmaster.item:
    description: Permission to use the /beast-item command.
    default: op

  beastmaster.loot:
    description: Permission to use the /beast-loot command.
    default: op

  beastmaster.mob:
    description: Permission to use the /beast-mob command.
    default: op

  beastmaster.obj:
    description: Permission to use the /beast-obj command.
    default: op

  beastmaster.admin:
    description: Permission to use all commands except those requiring console access.
    default: op
    children:
      beastmaster.zone: true
      beastmaster.item: true
      beastmaster.loot: true
      beastmaster.mob: true
      beastmaster.obj: true

commands:
  beastmaster:
    description: ${project.name} administrative command.
    permission: beastmaster.console
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> reload§f - Reload the configuration.
      
  beast-zone:
    description: Configure zones where beasts operate.
    permission: beastmaster.zone
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> add <zone-id> <world>§f - Add a new zone in the specified world.
      §e/<command> remove <zone-id>§f - Remove the definition of the specified zone.
      §e/<command> square <zone-id> <x> <z> <radius>§f - Set the square bounds of the zone to be a square centred on (x,z) with the specified radius (half side-length).
      §e/<command> list§f - List all zones.
      §e/<command> add-spawn <zone-id> <mob-id> <weight>§f - Add the specified mob as a replacement for hostile spawns in the identified zone with the given relative weight (or modify the weight).
      §e/<command> remove-spawn <zone-id> <mob-id>§f - Disable spawns of the specified mob in the given zone.
      §e/<command> list-spawns <zone-id>§f - List all spawns in the zone with the specified ID.
      §e/<command> add-block <zone-id> <material> <loot-id>§f - Add a block type to watch for break events. When a block of the specified material is broken, consult the specified loot table to see what drops. The <material> can be a case-insensitive Bukkit material name, or an integer ID.
      §e/<command> remove-block <zone-id> <material>§f - Remove the custom loot drop for the specified block type. The <material> can be a case-insensitive Bukkit material name, or an integer ID.
      §e/<command> list-blocks <zone-id>§f - List all block types in the zone that drop special loot, and their corresponding loot tables.

  beast-item:
    description: Configure items.
    permission: beastmaster.item
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> define <item-id>§f - Define a new item type as the thing held in the player's main hand. 
      §e/<command> redefine <item-id>§f - Redefine the specified item type as the thing held in the player's main hand. 
      §e/<command> remove <item-id>§f - Remove the definition of the specified item type.
      §e/<command> get <item-id> §f[§e<count>§f] - Give the player <count> of the item type with the specified, previously defined ID.
      §e/<command> list§f - List all item types.
      

  beast-loot:
    description: Configure loot tables.
    permission: beastmaster.loot
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> add <loot-id>§f - Define a new loot table. 
      §e/<command> remove <loot-id>§f - Remove the definition of the specified loot table.
      §e/<command> info <loot-id>§f - Describe the specified loot table.
      §e/<command> list§f - List all loot tables.
      §e/<command> add-drop <loot-id> <item-id> <percentage-chance> <min> [<max>]§f - Create or modify a drop in the loot table the mob, with an item type previously defined by /beast-item, and with the specified percentage chance in the range 0.0 to 100.0 and the specified number of items. If the maximum number is not specified, it defaults to the same as min.
      §e/<command> remove-drop <loot-id> <item-id>§f - Remove the specified item from the possible drops in the loot table.
      §e/<command> list-drops <loot-id>§f - List all possible drops from this loot table.
      §e/<command> single <loot-id> <yes-or-no>§f - Specifies whether a the loot table will drop a single drop or multiple independent drops. <yes-or-no> is case insensitive and can be one of yes/no/true/false/t/f/on/off. If yes, a single item stack will be selected to drop and drop chances are interpreted as relative preferences. If no, multiple items may drop, according to their drop chances.
      §e/<command> objective <loot-id> <item-id> (<obj-id>|none)§f - Signify that this drop causes an objective to spawn, or not if the objective ID is "none".
      §e/<command> sound <loot-id> <item-id> <sound> <range> <pitch>§f - NOT YET IMPLEMENTED. Signify that this drop causes a sound to play. <sound> is a sound name from the Bukkit API. <range> is the range of the sound in blocks. <pitch> is playback speed, from 0.5 to 2.0.
      §e/<command> xp <loot-id> <item-id> <xp>§f - NOT YET IMPLEMENTED. Signify that this drop will be accompanied by a specified amount of XP, or 0 to suppress the XP. NOTE: This option does not affect XP from vanilla default drops.

  beast-mob:
    description: Configure mobs.
    permission: beastmaster.mob
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> add <mob-id> <entity-type>§f - Define a new mob type as a mob with the specified Bukkit API entity type, e.g. ZOMBIE. 
      §e/<command> remove <mob-id>§f - Remove the definition of the specified mob type.
      §e/<command> info <mob-id>§f - Describe the specified mob type.
      §e/<command> list§f - List all mob types.
      §e/<command> health <mob-id> (<number>|default)§f - Override the health of the mob, or use the vanilla default.
      §e/<command> speed <mob-id> (<number>|default)§f - Override the speed of the mob, or use the vanilla default.
      §e/<command> baby-fraction <mob-id> (<number>|default)§f - Override the fraction of baby mobs [0..1.0], or use the vanilla default.
      
  beast-obj:
    description: Configure objectives.
    permission: beastmaster.obj
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> add <obj-id>§f - Define a new objective type. 
      §e/<command> remove <obj-id>§f - Remove the definition of the specified objective type.
      §e/<command> list§f - List all objective types.
      §e/<command> info <obj-id>§f - Describe the specified objective type.
      §e/<command> limit <obj-id> <max>§f - Specify the maximum number of objectives of the specified type in its zone.
      §e/<command> range <obj-id> <min> <max>§f - Specify the minimum and maximum range an objective can spawn from the drop that initiates it.
      §e/<command> height <obj-id> <min> <max>§f - Specify the minimum and maximum Y coordinate an objective can spawn.
      §e/<command> time <obj-id> <speed> <extra-ticks>§f - Specify the expected player speed from which objective lifetimes are computed. The <extra-ticks> value is a fixed amount of time added to the objective lifetime, irrespective of its range.
